import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import type { GatewayAuthority } from '../src/caller-context.js';
import { ArtifactPort } from '../src/artifact-harness/artifact-port.js';

const OWNER: GatewayAuthority = { ownerId: 'owner_bytes', sessionId: 'session_bytes', adapterId: 'private.stdio.v1' };

test('ArtifactPort createBytes stores generated bytes without invoking source-path authority', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'wag-artifact-bytes-'));
  let sourceChecks = 0;
  const port = new ArtifactPort({
    root: join(dir, 'store'),
    authorizeSource: async () => {
      sourceChecks += 1;
      throw new Error('must not run');
    },
    randomUUID: () => '00000000-0000-4000-8000-000000000301',
    now: () => 999,
  });
  t.after(() => rm(dir, { recursive: true, force: true }));

  const artifact = await port.createBytes(
    OWNER,
    'download?.txt',
    new TextEncoder().encode('generated\n'),
  );
  assert.equal(sourceChecks, 0);
  assert.equal(artifact.filename, 'download_.txt');
  assert.equal(artifact.sizeBytes, 10);
  assert.equal(await readFile(artifact.internalPath, 'utf8'), 'generated\n');
  assert.equal((await port.get(OWNER, artifact.artifactId)).sha256, artifact.sha256);
  const verified = await port.readBytes(OWNER, artifact.artifactId);
  assert.equal(Buffer.from(verified.bytes).toString('utf8'), 'generated\n');
  verified.bytes[0] = 0;
  assert.equal(await readFile(artifact.internalPath, 'utf8'), 'generated\n', 'returned bytes must not alias the artifact store');
});

test('ArtifactPort createBytes enforces the same artifact size ceiling', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'wag-artifact-bytes-'));
  const port = new ArtifactPort({
    root: join(dir, 'store'),
    authorizeSource: async (_owner, requested) => requested,
    maxBytes: 4,
  });
  t.after(() => rm(dir, { recursive: true, force: true }));

  await assert.rejects(
    () => port.createBytes(OWNER, 'too-big.bin', new Uint8Array([1, 2, 3, 4, 5])),
    /bytes exceed size limit/,
  );
  assert.deepEqual(await port.list(OWNER), []);
});
